name: 3rd Party Dependency Check

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'package.json'
      - 'package-lock.json'

jobs:
  check-3rd-party:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures all history is fetched

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use the node version compatible with your project

      - name: Check for 3rd Party Dependencies
        id: check_dependencies
        run: |
          # Install required tools
          sudo apt-get install -y jq

          # Fetch the base branch
          git fetch origin ${{ github.base_ref }}
          git checkout ${{ github.base_ref }}
          git checkout -

          # Initialize a flag
          echo "DEPENDENCY_CHANGE=false" >> $GITHUB_ENV

          # Compare package.json
          echo "Checking package.json for changes..."
          if git diff --name-only origin/${{ github.base_ref }}...HEAD | grep 'package.json'; then
            echo "Changes detected in package.json"
            echo "DEPENDENCY_CHANGE=true" >> $GITHUB_ENV
          fi

          # Compare package-lock.json
          echo "Checking package-lock.json for changes..."
          if git diff --name-only origin/${{ github.base_ref }}...HEAD | grep 'package-lock.json'; then
            echo "Changes detected in package-lock.json"
            echo "DEPENDENCY_CHANGE=true" >> $GITHUB_ENV
          fi

      - name: Post Comment
        if: ${{ env.DEPENDENCY_CHANGE == 'true' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### New 3rd Party Dependency Justification
            Changes in `package.json` or `package-lock.json` detected. Please fill out the form below to justify the inclusion of new 3rd party dependencies.

            <!-- 3rd party dependency justification markdown form -->
            | Topic      | Questions/considerations | Answer |
            | ----------- | ----------- | ----------- |
            | **Problem statement** | What problem does using this package solve for us? |   |
            | **Cost/subscription** | At this time, we will not accept any libraries that are paid. |   |
            | **Community** | Is there a robust community using this package? |   |
            | **Maintenance** | How often is the package updated? |   |
            | **Data privacy** | If our data will be processed through this tool, please verify that data is not being collected or sold. |   |
            | **Security** | Verify that the package does not install malicious code. |   |
            | **Maintainability** | Does using this require a specialized skill set or have a steep learning curve? |   |
            | **Other options** | What other options have you considered? |   |
            | **Can we do it ourselves** | Why is an external solution better than a custom solution of our own? |   |
            | **Other notes** | Any other information you would like to share? |   |

            Please edit this comment to fill out the form.
