name: Markdown Component Check

on:
  pull_request:
    branches:
      - main

jobs:
  check_markdown_components:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check for Markdown Components
        run: |
          # Get the branch name from github.ref
          BRANCH_NAME=$(echo ${{ github.ref }} | awk -F'/' '{print $NF}')

          # Find files changed in the PR
          PR_FILES=$(git diff --name-only main $BRANCH_NAME)

          # Use grep to search for Material-UI Markdown components in changed files
          if echo "$PR_FILES" | xargs grep -l 'MuiMarkdown' ; then
            echo "Material-UI markdown components found in code changes. Rejecting PR."
            exit 1
          fi
        shell: bash
