name: Markdown Component Check

on:
  pull_request:
    branches:
      - main

jobs:
  check_markdown_components:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check for Markdown Components
        run: |
          # Determine the base branch based on the pull request action
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            BASE_BRANCH=${{ github.base_ref }}
          else
            BASE_BRANCH="main"
          fi

          # Fetch the branch to ensure it's available
          git fetch origin $BASE_BRANCH:$BASE_BRANCH

          # Find files changed in the PR
          PR_FILES=$(git diff --name-only $BASE_BRANCH ${{ github.head_ref }})

          # Use grep to search for Material-UI Markdown components in changed files
          if echo "$PR_FILES" | xargs grep -l 'MuiMarkdown' ; then
            echo "Material-UI markdown components found in code changes. Rejecting PR."
            exit 1
          fi
        shell: bash
