name: Markdown Component Check

on:
  pull_request:
    branches:
      - main

jobs:
  check_markdown_components:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Determine Opening Branch
        run: |
          # Determine the branch opening the PR using GitHub API
          OPENING_BRANCH=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
          | jq -r '.head.ref')

          # Find files changed in the PR
          PR_FILES=$(git diff --name-only ${{ github.base_ref }} $OPENING_BRANCH)

          # Use grep to search for Material-UI Markdown components in changed files
          if echo "$PR_FILES" | xargs grep -l 'MuiMarkdown' ; then
            echo "Material-UI markdown components found in code changes. Rejecting PR."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        shell: bash
