name: Markdown Component Check

on:
  pull_request:
    branches:
      - main

jobs:
  check_markdown_components:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch Main Branch
        run: git fetch origin main:main

      - name: Determine Opening Branch
        run: |
          # Determine the branch opening the PR using GitHub API
          OPENING_BRANCH=$(curl -s -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
          | jq -r '.head.ref')

      - name: Fetich Opening Branch
        run: |
          # Fetch the branch opening the PR
          git fetch origin $OPENING_BRANCH:$OPENING_BRANCH

      - name: Find Changed files
        run: |
          # Find files changed in the PR
          PR_FILES=$(git diff --name-only main $OPENING_BRANCH)

      - name: Search for Markdown components
        run: |
          # Use grep to search for Material-UI Markdown components in changed files
          MUI_MARKDOWN_FOUND=0
          for file in $PR_FILES; do
            if [[ "$file" != *".yml" ]] && grep -q 'MuiMarkdown' "$file"; then
              MUI_MARKDOWN_FOUND=1
              break
            fi
          done

          if [ $MUI_MARKDOWN_FOUND -eq 1 ]; then
            echo "Material-UI markdown components found in code changes. Rejecting PR."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        shell: bash
