name: Markdown Component Check

on:
  pull_request:
    branches:
      - main

jobs:
  check_markdown_components:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch Main Branch
        run: git fetch origin main:main

      - name: Determine Opening Branch
        run: |
          # Determine the branch opening the PR using GitHub API
          OPENING_BRANCH=$(curl -s -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
          | jq -r '.head.ref')

          # Set the environment variable to be used later
          echo "OPENING_BRANCH=$OPENING_BRANCH" >> $GITHUB_ENV

      - name: Fetch Opening Branch
        run: |
          # Fetch the branch opening the PR
          git fetch origin $OPENING_BRANCH:$OPENING_BRANCH

      - name: Find Changed files
        run: |
            # Find files changed in the PR
            PR_FILES=$(git diff --name-only main $OPENING_BRANCH)
        
            # Set the environment variable to be used later
            echo "PR_FILES=$PR_FILES" >> $GITHUB_ENV
        env:
            OPENING_BRANCH: ci3

      - name: Search for Markdown components
        run: |
          # Use grep to search for Material-UI Markdown components in changed files
          MUI_MARKDOWN_FOUND=0
          for file in $PR_FILES; do
            if [[ "$file" != *".yml" ]] && grep -q 'MuiMarkdown' "$file"; then
              MUI_MARKDOWN_FOUND=1
              break
            fi
          done

          if [ $MUI_MARKDOWN_FOUND -eq 1 ]; then
            echo "Material-UI markdown components found in code changes. Rejecting PR."
            echo "::set-output name=pr_rejected::true" # Set an output parameter
          else
            echo "No Material-UI markdown components found in code changes. PR is safe to merge."
            echo "::set-output name=pr_rejected::false" # Set an output parameter
          fi

      - name: Set job summary
        run: |
          if [[ $pr_rejected == "true" ]]; then
            echo "Material-UI markdown components found in code changes. Rejecting PR." >> $GITHUB_STEP_SUMMARY
          else
            echo "No Material-UI markdown components found in code changes. PR is safe to merge." >> $GITHUB_STEP_SUMMARY
          fi
