# Sample workflow for building and deploying a Next.js site to GitHub Pages for each branch
name: Deploy Next.js site to GitHub Pages

on:
  pull_request:
    types:
      - opened

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies with Bun
        run: bun install

      - name: Build with Next.js and Bun
        run: bun run build

      - name: Build and Deploy to GitHub Pages
        run: |
          npm run build
          npm run export
          git checkout -B ${{ github.event.pull_request.head.ref }}
          cp -r out/* .
          git add .
          git commit -m "Deploy to GitHub Pages for PR: ${{ github.event.pull_request.number }}"
          git push -u origin ${{ github.event.pull_request.head.ref }}

      - name: Create Pull Request Comment
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d '{"body": "Staging site deployed for this pull request: https://sramalho94.github.io/Bun_Portfolio/${{ github.event.pull_request.head.ref}}" }' "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number}}/comments"

